steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'bb-worker/Dockerfile.debian8', '--tag=gcr.io/zcash-web/bb-worker-debian8', 'bb-worker/']
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'bb-worker/Dockerfile.debian9', '--tag=gcr.io/zcash-web/bb-worker-debian9', 'bb-worker/']
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'bb-worker/Dockerfile.debian10', '--tag=gcr.io/zcash-web/bb-worker-debian10', 'bb-worker/']
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'bb-worker/Dockerfile.ubuntu1604', '--tag=gcr.io/zcash-web/bb-worker-ubuntu1604', 'bb-worker/']
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'bb-worker/Dockerfile.ubuntu1804', '--tag=gcr.io/zcash-web/bb-worker-ubuntu1804', 'bb-worker/']
    waitFor: ['-']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'bb-worker/Dockerfile.ubuntu1904', '--tag=gcr.io/zcash-web/bb-worker-ubuntu1904', 'bb-worker/']
    waitFor: ['-']
images:
  - gcr.io/zcash-web/bb-worker-debian8
  - gcr.io/zcash-web/bb-worker-debian9
  - gcr.io/zcash-web/bb-worker-debian10
  - gcr.io/zcash-web/bb-worker-ubuntu1604
  - gcr.io/zcash-web/bb-worker-ubuntu1804
  - gcr.io/zcash-web/bb-worker-ubuntu1904